#
# Learn more about this Gitpod configuration file in the documentation at https://www.gitpod.io/docs/configuration
#
ports:
  - port: 24678
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks
tasks:
  - init: npm install
    command: |
      echo "Applying a temporary HMR workaround until https://github.com/vitejs/vite/pull/1992 is fixed."
      (
        cd ./node_modules/vite/dist/node/chunks/ &&
        sed -i 's/JSON.stringify(port)/JSON.stringify(443)/g' * &&
        export WSS_HOST=`gp url 24678 | sed 's#https://##g'` &&
        sed -i "s#JSON.stringify(host)#JSON.stringify(\"$WSS_HOST\")#g" *
      )
      (
        RED='\033[0;31m'
        BOLD='\033[1;30m'
        NC='\033[0m' # No Color

        gp env | grep --quiet VITE_SUPABASE_URL
        if [ $? -eq 1 ]
        then
          printf "${RED}Missing environment variables for supabase.${NC}\n\n"
          printf "To configure them:\n\n1. run: ${BOLD}gp env -e VITE_SUPABASE_URL=your_supabase_url VITE_SUPABASE_ANON_KEY=your_supabase_anon_key${NC}\n2. stop and re-start your workspace\n"
        else
          npm run dev
        fi
      )

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    - svelte.svelte-vscode
